# Generated by Django 4.0.3 on 2023-01-23 01:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('plays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=9)),
                ('spaces', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), size=9)),
                ('privacy', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
