# Generated by Django 4.0.3 on 2023-01-24 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fifteen_toes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='game',
            name='loser',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player_one',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player_two',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='games_finished',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='games_forfeited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='loss_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='win_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
