# Generated by Django 4.0.3 on 2023-02-02 21:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteen_toes', '0003_lobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='lobby',
            name='privacy',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='game',
            name='plays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=9),
        ),
        migrations.AlterField(
            model_name='game',
            name='spaces',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), default=list, size=9),
        ),
    ]
