# Generated by Django 4.0.3 on 2023-02-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteen_toes', '0004_lobby_password_lobby_privacy_alter_game_plays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='p1_status',
            field=models.CharField(default='UNREADY', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='p2_status',
            field=models.CharField(default='UNREADY', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='game',
            name='privacy',
            field=models.CharField(default='Public', max_length=7),
        ),
        migrations.DeleteModel(
            name='Lobby',
        ),
    ]
