# Generated by Django 4.0.3 on 2023-03-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteen_toes', '0005_game_p1_status_game_p2_status_alter_game_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('ended', models.DateTimeField()),
            ],
        ),
    ]
