# Generated by Django 4.0.3 on 2023-03-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteen_toes', '0006_gamearchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamearchive',
            name='p1_status',
            field=models.CharField(default='COMPLETED', max_length=10),
        ),
        migrations.AddField(
            model_name='gamearchive',
            name='p2_status',
            field=models.CharField(default='COMPLETED', max_length=10),
        ),
        migrations.AddField(
            model_name='gamearchive',
            name='player_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamearchive',
            name='player_two',
            field=models.IntegerField(default=0),
        ),
    ]
