# Generated by Django 4.0.3 on 2023-03-04 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifteen_toes', '0007_gamearchive_p1_status_gamearchive_p2_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameArchive',
        ),
    ]
