# Generated by Django 4.0.3 on 2023-03-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifteen_toes', '0008_delete_gamearchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one', models.IntegerField(default=0)),
                ('p1_status', models.CharField(default='COMPLETED', max_length=10)),
                ('player_two', models.IntegerField(default=0)),
                ('p2_status', models.CharField(default='COMPLETED', max_length=10)),
                ('created', models.DateTimeField()),
                ('ended', models.DateTimeField()),
            ],
        ),
    ]
