# Generated by Django 4.0.3 on 2023-03-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifteen_toes', '0009_gamearchive'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameArchive',
        ),
    ]
