# Generated by Django 4.2 on 2023-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fifteen_toes", "0010_delete_gamearchive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="round",
            field=models.IntegerField(default=1),
        ),
    ]
