# Generated by Django 4.2 on 2023-05-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fifteen_toes", "0011_alter_game_round"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("content", models.TextField()),
            ],
        ),
    ]
