# Generated by Django 4.2 on 2023-05-01 21:18

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("fifteen_toes", "0012_gameinstruction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameinstruction",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
