# Generated by Django 4.0.3 on 2022-10-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('food', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'allergies',
                'managed': False,
            },
        ),
    ]
