# Generated by Django 4.0.3 on 2022-10-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='content1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='href1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='href2',
            field=models.TextField(default=''),
        ),
    ]
