# Generated by Django 4.0.3 on 2022-10-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_content_post_content1_post_content2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweetContent',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='tweetHref',
            field=models.TextField(default=''),
        ),
    ]
