# Generated by Django 4.0.3 on 2022-10-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_href1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tweetContent',
        ),
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content3',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='href2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetHref',
            field=models.TextField(),
        ),
    ]
