# Generated by Django 4.0.3 on 2022-10-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_tweetcontent_alter_post_content2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='href1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='href2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweetHref',
            field=models.TextField(blank=True),
        ),
    ]
