# Generated by Django 4.0.3 on 2022-10-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tweetcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweetUser',
            field=models.TextField(blank=True),
        ),
    ]
