# Generated by Django 4.0.3 on 2022-10-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tweetuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tweetDate',
            field=models.TextField(blank=True),
        ),
    ]
