# Generated by Django 4.0.3 on 2022-10-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_tweetdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hrefName1',
            field=models.TextField(blank=True),
        ),
    ]
