# Generated by Django 4.0.3 on 2022-10-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_hrefname1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hrefName2',
            field=models.TextField(blank=True),
        ),
    ]
