# Generated by Django 4.0.3 on 2023-01-07 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_hrefname2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='href1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='href2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hrefName1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hrefName2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tweetContent',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tweetDate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tweetHref',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tweetUser',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
