# Generated by Django 5.0.7 on 2024-09-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="display_content",
            field=models.BooleanField(default=True),
        ),
    ]
